/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.evotechsoftwaresolutions.evemp.gui;

import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.Dimension;
import java.lang.reflect.Array;
import javax.swing.JPanel;

/**
 *
 * @author slknew
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        init();
    }

    private JPanel active;

    private void init() {
        this.setExtendedState(MAXIMIZED_BOTH);
//        this.setResizable(false);
        this.setLocationRelativeTo(null);
        jPanel8.setVisible(false);
        jPanel9.setVisible(false);
        jPanel10.setVisible(false);
        jPanel11.setVisible(false);
        showPanel(jPanel8);
    }

    private void showPanel(JPanel newPanel) {
        if (active != null) {
            active.setVisible(false);
        }
        newPanel.setVisible(true);
        active = newPanel;
    }

    public void switchScreen(int index){
        switch (index) {
            case 1:
                jLabel3.setText("Dashboard");
                showPanel(jPanel8);
                break;
            case 2:
                jLabel3.setText("Quotations");
                showPanel(jPanel9);
                break;
            case 3:
                jLabel3.setText("Invoices");
                showPanel(jPanel10);
                break;
            case 4:
                jLabel3.setText("Customers");
                showPanel(jPanel11);
                break;
            default:
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(2, 0), new java.awt.Dimension(2, 0), new java.awt.Dimension(2, 4));
        jButton2 = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(2, 0), new java.awt.Dimension(2, 0), new java.awt.Dimension(2, 4));
        jButton3 = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(2, 0), new java.awt.Dimension(2, 0), new java.awt.Dimension(2, 4));
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(32767, 0));
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 32767));
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 32767));
        filler11 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(32767, 0));
        jPanel15 = new javax.swing.JPanel();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(75, 0), new java.awt.Dimension(250, 0), new java.awt.Dimension(300, 0));
        jTextField1 = new javax.swing.JTextField();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 50), new java.awt.Dimension(10, 10), new java.awt.Dimension(32767, 50));
        jButton6 = new javax.swing.JButton();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(75, 0), new java.awt.Dimension(150, 0), new java.awt.Dimension(300, 0));
        jButton7 = new javax.swing.JButton();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(15, 0), new java.awt.Dimension(40, 0), new java.awt.Dimension(100, 0));
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setAlignmentY(15.0F);
        jPanel3.setMinimumSize(new java.awt.Dimension(50, 50));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(218, 218, 218));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 85));
        jPanel2.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("EVOTECH");
        jLabel1.setAlignmentY(5.0F);
        jPanel2.add(jLabel1);

        jPanel3.add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel5.setBackground(new java.awt.Color(218, 218, 218));
        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(25, 5, 1, 5));
        jPanel5.setOpaque(false);
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.Y_AXIS));

        jButton1.setText("Dashboard");
        jButton1.setMargin(new java.awt.Insets(5, 14, 5, 14));
        jButton1.setMaximumSize(new Dimension(Integer.MAX_VALUE, jButton1.getPreferredSize().height));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1);
        jPanel5.add(filler1);

        jButton2.setText("Quotations");
        jButton2.setMargin(new java.awt.Insets(5, 14, 5, 14));
        jButton2.setMaximumSize(new Dimension(Integer.MAX_VALUE, jButton2.getPreferredSize().height));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2);
        jPanel5.add(filler2);

        jButton3.setText("Invoices");
        jButton3.setMargin(new java.awt.Insets(5, 14, 5, 14));
        jButton3.setMaximumSize(new Dimension(Integer.MAX_VALUE, jButton3.getPreferredSize().height));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3);
        jPanel5.add(filler3);

        jButton4.setText("Customers");
        jButton4.setMargin(new java.awt.Insets(5, 14, 5, 14));
        jButton4.setMaximumSize(new Dimension(Integer.MAX_VALUE, jButton4.getPreferredSize().height));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton4);

        jPanel3.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel4.setBackground(new java.awt.Color(218, 218, 218));
        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 5, 25, 5));
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.BorderLayout());

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 0, 0));
        jButton5.setText("Log out");
        jButton5.putClientProperty("JButton.buttonType", "custom");
        jButton5.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, true), javax.swing.BorderFactory.createEmptyBorder(5, 1, 5, 1)));
        jButton5.setMargin(new java.awt.Insets(6, 14, 6, 14));
        jButton5.setMaximumSize(new Dimension(Integer.MAX_VALUE, jButton5.getPreferredSize().height));
        jPanel4.add(jButton5, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel3, java.awt.BorderLayout.WEST);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 1));
        jPanel7.setLayout(new java.awt.GridLayout(0, 1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Dashboard");
        jPanel7.add(jLabel3);

        jPanel1.add(jPanel7, java.awt.BorderLayout.NORTH);

        jPanel6.setLayout(new java.awt.CardLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new java.awt.BorderLayout());
        jPanel8.add(jPanel13, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel8, "card2");

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jPanel14.setLayout(new java.awt.BorderLayout());
        jPanel14.add(filler10, java.awt.BorderLayout.LINE_END);
        jPanel14.add(filler6, java.awt.BorderLayout.PAGE_END);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Q ID", "Customer Name", "Issued Date", "Expiry Date", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel14.add(jScrollPane1, java.awt.BorderLayout.CENTER);
        jPanel14.add(filler9, java.awt.BorderLayout.PAGE_START);
        jPanel14.add(filler11, java.awt.BorderLayout.LINE_START);

        jPanel9.add(jPanel14, java.awt.BorderLayout.CENTER);

        jPanel15.setLayout(new javax.swing.BoxLayout(jPanel15, javax.swing.BoxLayout.LINE_AXIS));
        jPanel15.add(filler7);

        jTextField1.setMargin(new java.awt.Insets(5, 6, 5, 6));
        jTextField1.setPreferredSize(new java.awt.Dimension(500, 25));
        jPanel15.add(jTextField1);
        jPanel15.add(filler4);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/evotechsoftwaresolutions/evemp/img/search.png"))); // NOI18N
        jButton6.setMaximumSize(new java.awt.Dimension(76, 40));
        jButton6.setMinimumSize(new java.awt.Dimension(10, 27));
        jButton6.setPreferredSize(new java.awt.Dimension(27, 27));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel15.add(jButton6);
        jPanel15.add(filler8);

        jButton7.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jButton7.setText("New Quotation");
        jButton7.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)), javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10)));
        jButton7.putClientProperty("JButton.arc", 50);
        jPanel15.add(jButton7);
        jPanel15.add(filler5);

        jPanel9.add(jPanel15, java.awt.BorderLayout.NORTH);

        jPanel6.add(jPanel9, "card3");

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.add(jPanel10, "card4");
        jPanel6.add(jPanel11, "card5");

        jPanel1.add(jPanel6, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        switchScreen(1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        switchScreen(2);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        switchScreen(3);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        switchScreen(4);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        FlatLightLaf.setup();
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler11;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
